version: '3.5'
services:
  mongodb:
    image: mongo
    container_name: course-nodejs-rest-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    command: --wiredTigerCacheSizeGB 2
