# Получить объявление по идентификатору
GET http://localhost:4000/offers/62711a50b0e24a624d49ffdc HTTP/1.1

###

## Получить список объявлений
GET http://localhost:4000/offers HTTP/1.1

###

## Создать новое объявление

POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Билли Саммерс",
  "description": "Новый детективный роман от короля ужасов.",
  "postDate": "2022-05-12T11:56:37.573Z",
  "image": "billy-summers.png",
  "type": "Sell",
  "price": 1408,
  "categories": ["65258514a30fc6ef77c0edf2", "65258514a30fc6ef77c0ee01"],
  "userId": "62823cb2c5a64ce9f1b50ec8"
}

###

## Удалить объявление по идентификатору

DELETE http://localhost:4000/offers/62825028a75295825778ac80 HTTP/1.1

###

## Обновить объявление

PATCH http://localhost:4000/offers/652e71c6d9f30c786a73f139 HTTP/1.1
Content-Type: application/json

{
  "title": "Ночной дозор 3",
  "description": "Проверка обновления",
  "price": 1100
}

###

## Список объявлений определённой категории

GET http://localhost:4000/categories/65258514a30fc6ef77c0edfe/offers?limit=10 HTTP/1.1

###

## Список комментариев к объявлению
GET http://localhost:4000/offers/628a27d729c45f2bf9f6806a/comments HTTP/1.1

###
